# Generated by Django 5.1.5 on 2025-01-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_generation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="prompt_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
