# Generated by Django 5.1.5 on 2025-02-02 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image_generation", "0004_agent_chat_chatmessage_delete_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
